### ISSUE TITLE
第三章第四节View事件分发机制中（141页），onInterceptTouchEvent与onTouchEvent关系讲解错误

### ISSUE THREAD

**Issue by MaAnQing** [singwhatiwanna/android-art-res#8]
书中描述两者关系如下，

	public boolean dispatchTouchEvent(MotionEvent ev) {
    	boolean consume = false;
    	if (onInterceptTouchEvent(ev)) {
        	consume = onTouchEvent(ev);
    	} else {
        	consume = child.dispatchTouchEvent(ev);
    	}
    	return consume;
	}
但我在实际开发中，我遇到onInterceptTouchEvent返回false时仍会触发onTouchEvent事件，所以上述两者关系描述错误

**Comment by singwhatiwanna** [comment]
@MaAnQing 这段是伪代码，主要是为了描述三者之间的关系，并非实际的代码。

**Comment by MaAnQing** [comment]
@singwhatiwanna 我知道这是伪代码，按照这段伪代码可知当onInterceptTouchEvent(ev)返回为true时才会调用onTouchEvent(ev)，但我在实际开发中，我遇到onInterceptTouchEvent返回false时仍会触发onTouchEvent事件，这样是不是就说明上述为代码有问题，是不是说明三者之间的关系并非为上述为伪代码所描述的那样

**Comment by Kutear** [comment]
onInterceptTouchEvent返回false表示ViewGroup不拦截这个事件,自然会分发到子View,但是如果子View的onTouch/onTouchEvent同样返回false,即子View不处理该事件,事件又会回到上级ViewGroup处理,即你说的调用onTouchEvent.刚看本书,不知理解是否正确

**Comment by singwhatiwanna** [comment]
@MaAnQing 你说的那个问题书中有详细说明，我也理解。上面那段伪代码，如果考虑到各种情况，那就不能那么简洁了，就没有意义了，还请分别去理解。

**Comment by MaAnQing** [comment]
@Kutear 应该就是你讲的那样，没有验证
